# Declare and configure plugins
plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# https://nicolas-van.github.io/easy-markdown-to-github-pages/
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

# Site metadata
title: "BrotherEarth967"
description: "@ brotherearth967.github.com"

# Syntax configuration
markdown: kramdown

# Default YAML frontmatter values
defaults:
  -
    # set default layout to "default"
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      title: "Click to Add Title"
